### ISSUE TITLE
Issues Generating The Trimmed OSM.PBF File

### ISSUE THREAD

**Issue by galdi** [OpenSidewalks/opensidewalks_cli#2]
It looks like the osmium extract step is not producing a usable OSM.PBF file that can be used in the last step to generate the task files for Baltimore. The extract step completes the process without error. Yet, the file that was produced was suspiciously small, and did not load data into QGIS--attributes all appear NULL. I have confirmed that the original OSM.PBF file, downloaded from geofabrik, for the state of Maryland has no issues.

The files below include the original Maryland OSM.PBF data, the baltimore_johnsHopkins.geojson file that was extracted from geojson.io. Both files were verified in QGIS. The trimmed file that was generated in the extract step is named baltimore-jh-error.osm.pbf.

The file set has been included in a zip file that can be downloaded here: [https://drive.google.com/file/d/1fGWq977ghOOtf9_ghrzlshKY_79jFAKq/view?usp=share_link]

**Comment by galdi** [comment]
The error that resulted when I ran the osw task script is:
(opensidewalks-cli-uBeWZQSC-py3.8) galdi@DESKTOP-7DCCR3V:~/projects/osw/opensidewalks_cli/staging_directory/baltimore$ poetry run osw task data_sources/baltimore-jh.osm.pbf intermediate_data/baltimore_johnsHopkins.geojson output/
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/galdi/.cache/pypoetry/virtualenvs/opensidewalks-cli-uBeWZQSC-py3.8/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/galdi/.cache/pypoetry/virtualenvs/opensidewalks-cli-uBeWZQSC-py3.8/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/galdi/.cache/pypoetry/virtualenvs/opensidewalks-cli-uBeWZQSC-py3.8/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/galdi/.cache/pypoetry/virtualenvs/opensidewalks-cli-uBeWZQSC-py3.8/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/galdi/.cache/pypoetry/virtualenvs/opensidewalks-cli-uBeWZQSC-py3.8/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/galdi/projects/osw/opensidewalks_cli/opensidewalks_cli/cli.py", line 30, in task
    extract_crossing_tasks(osm_file, area_geojson, output_dir)
  File "/home/galdi/projects/osw/opensidewalks_cli/opensidewalks_cli/tasks/crossing_tasks.py", line 95, in extract_crossing_tasks
    raise Exception(
Exception: No intersections! Is your area of interest within the OSM file?
(opensidewalks-cli-uBeWZQSC-py3.8) galdi@DESKTOP-7DCCR3V:~/projects/osw/opensidewalks_cli/staging_directory/baltimore
